databases:
  - name: financial-app-db
    databaseName: financial_app_db
    user: financial_app_user
    plan: free

services:
  # Web Service for the Flask App
  - name: financial-app-backend
    type: web
    runtime: python
    plan: free
    buildCommand: "find . -type f -name \"*.pyc\" -delete && pip install -r financial_app/backend/backend_app/requirements.txt"
    healthCheckPath: /api/health
    startCommand: "gunicorn --chdir financial_app/backend/backend_app wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.4"
      - key: FLASK_CONFIG
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: financial-app-db
          property: connectionString
