databases:
  - name: financial-app-db
    databaseName: financial_app_db
    user: financial_app_user
    plan: free

services:
  # Web Service for the Flask App
  - name: financial-app-backend
    type: web
    runtime: python
    plan: free
    buildCommand: "pip install -r financial_app/backend/backend_app/requirements.txt"
    startCommand: "gunicorn --chdir financial_app/backend/backend_app 'src.main:create_app()'"
    envVars:
      - key: FLASK_CONFIG
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: financial-app-db
          property: connectionString
