databases:
  - name: financial-app-db
    databaseName: financial_app_db
    user: financial_app_user
    plan: free

services:
  # Web Service for the Flask App
  - name: financial-app-backend
    type: web
    runtime: python
    plan: free
    buildCommand: "find . -type f -name \"*.pyc\" -delete && pip install -r financial_app/backend/backend_app/requirements.txt"
    healthCheckPath: /api/health
    startCommand: "flask db upgrade && gunicorn --chdir financial_app/backend/backend_app wsgi:app"
    envVars:
      - key: PYTHONPATH
        value: "."
      - key: FLASK_APP
        value: "financial_app/backend/backend_app/wsgi.py"
      - key: PYTHON_VERSION
        value: "3.12.4"
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FLASK_CONFIG
        value: production
      - key: CORS_ORIGINS
        value: "https://financial-app-frontend.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: financial-app-db
          property: connectionString
