openapi: 3.0.0
info:
  title: Financial App API
  description: API for managing personal finances, including transactions, goals, and investments.
  version: "1.0.0"
servers:
  - url: /api
    description: API Root
security:
  - cookieAuth: []

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: access_token_cookie
    apiKey:
      type: apiKey
      in: header
      name: X-API-KEY
      description: "API Key for administrative endpoints"

paths: {}  # As rotas ser√£o preenchidas automaticamente pelo Flasgger
