name: Deploy to PythonAnywhere via SSH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Add PythonAnywhere to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ssh.pythonanywhere.com >> ~/.ssh/known_hosts

      - name: Execute deployment script on PythonAnywhere
        uses: appleboy/ssh-action@master
        with:
          host: ssh.pythonanywhere.com
          username: "Mackenzie"
          password: ${{ secrets.PA_PASSWORD }}
          debug: true
          script: |
            /home/Mackenzie/deploy.sh
